"""
train_xgb_source_kfold_optuna.py

1. Read the 5-fold data in splits/source_kfold/ (generated by split_dataset.py)
2. Perform global hyperparameter search across the 5 folds using Optuna, with the average R2 as the optimization target
3. Retrain the model on each fold with the optimal global hyperparameters obtained
4. For each individual fold:
   - Print the R2 and MAE values
   - Save the model of the current fold via joblib
   - Save the metadata of the current fold in JSON format
5. Save the summary table of results from all folds and the Optuna trial table

Notes:
- Keep the feature columns exactly the same as those defined in split_dataset.py.
——————————————————————
功能：
1. 读取 splits/source_kfold/ 中的 5 折数据（由 split_dataset.py 生成）
2. 使用 Optuna 在 5 折上做全局超参数搜索（以平均 R2 为目标）
3. 用找到的全局最佳超参数在每一折上重新训练模型
4. 对每一折：
   - 打印 R2 / MAE
   - 保存该折模型（joblib）
   - 保存该折的元信息（json）
5. 保存所有折结果汇总表、Optuna trial 表

注意：
- 特征列与 split_dataset.py 中保持完全一致。
"""

import os
from pathlib import Path
import json

import numpy as np
import pandas as pd

from sklearn.metrics import r2_score, mean_absolute_error

import xgboost as xgb
import optuna
from joblib import dump  # 用于保存模型

# =========================
# 配置区域
# =========================

# 使用 source-aware 的 5 折数据集
DATA_DIR = Path("splits/random_kfold")

# 模型和结果输出目录
MODEL_DIR = Path("models/xgb_random_kfold")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

# 超参数搜索的 trial 数
N_TRIALS = 150

# 特征列（与 split_dataset.py 完全一致）
ht_cols = [
    "solu_temp", "solu_time",
    "middle_temp", "middle_time",
    "aging_temp", "aging_time",
]

comp_cols = [
    "x_Co", "x_Al", "x_W", "x_Ni", "x_Cr", "x_Mo", "x_Fe", "x_Nb",
    "x_C", "x_Hf", "x_Si", "x_Ta", "x_Ti", "x_Y", "x_V", "x_B",
    "x_Zr", "x_Mn", "x_Sc", "x_La", "x_Re",
]

feature_cols = ht_cols + comp_cols + [
    "Temperature",
    "has_solu", "has_middle", "has_aging",
]

target_col = "lgkp"


# =========================
# 工具函数
# =========================

def load_fold_data(fold_id: int):
    """
    从 splits/random_kfold/ 中加载某一折的 train/test 数据
    """
    train_path = DATA_DIR / f"fold{fold_id}_train.csv"
    test_path  = DATA_DIR / f"fold{fold_id}_test.csv"

    if not train_path.exists() or not test_path.exists():
        raise FileNotFoundError(f"Fold {fold_id} CSV not found in {DATA_DIR}")

    df_train = pd.read_csv(train_path)
    df_test  = pd.read_csv(test_path)

    X_train = df_train[feature_cols].values
    y_train = df_train[target_col].values

    X_test = df_test[feature_cols].values
    y_test = df_test[target_col].values

    return X_train, y_train, X_test, y_test, df_train, df_test


def preload_all_folds():
    """
    预加载 5 折数据到内存，避免重复读盘。
    返回字典 folds_data[fold_id] = {...}
    """
    folds_data = {}
    for fold in range(1, 6):
        X_tr, y_tr, X_te, y_te, df_tr, df_te = load_fold_data(fold)
        folds_data[fold] = {
            "X_train": X_tr,
            "y_train": y_tr,
            "X_test": X_te,
            "y_test": y_te,
            "df_train": df_tr,
            "df_test": df_te,
        }
        print(
            f"Fold {fold}: "
            f"train={len(y_tr)}, test={len(y_te)}, "
            f"train_sources={df_tr['source_key'].nunique()}, "
            f"test_sources={df_te['source_key'].nunique()}"
        )
    return folds_data


# =========================
# Optuna 目标函数
# =========================

def optuna_objective_global(trial, folds_data):
    """
    Optuna 的目标函数：给定一组超参数，在 5 折上分别训练+验证，
    取平均 R2，返回其相反数（因为 Optuna 默认最小化）。
    """
    # 待优化的超参数空间
    params = {
        "objective": "reg:squarederror",
        "eval_metric": "rmse",
        "booster": "gbtree",
        "tree_method": "hist",
        "random_state": 42,

        # 核心
        "max_depth": trial.suggest_int("max_depth", 4, 50),
        "learning_rate": trial.suggest_float("learning_rate", 0.0001, 0.01, log=True),
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),
        "min_child_weight": trial.suggest_float("min_child_weight", 2.0, 10.0),

        # 泛化
        "subsample": trial.suggest_float("subsample", 0.1, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.1, 1.0),

        # 正则
        "gamma": trial.suggest_float("gamma", 0.1, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.1, 1.0),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.1, 1.0),
        # 如果你想限制线程数，可以加上:
        "n_jobs": 8,
    }

    r2_scores = []

    # 在 5 个 source_kfold 上分别训练+验证，取平均 R2
    for fold in range(1, 6):
        X_train = folds_data[fold]["X_train"]
        y_train = folds_data[fold]["y_train"]
        X_test  = folds_data[fold]["X_test"]
        y_test  = folds_data[fold]["y_test"]

        model = xgb.XGBRegressor(**params)
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        r2 = r2_score(y_test, y_pred)
        r2_scores.append(r2)

    mean_r2 = float(np.mean(r2_scores))
    # 希望 R2 越大越好 → 返回负的平均 R2
    return -mean_r2


# =========================
# 主流程
# =========================

def main():
    # 1. 预加载 5 折数据
    print("=== Preloading 5-fold source-aware datasets ===")
    folds_data = preload_all_folds()

    # 2. 使用 Optuna 搜索全局最佳超参数
    print("\n=== Start Optuna Hyperparameter Optimization ===")
    study = optuna.create_study(direction="minimize", study_name="xgb_source_kfold_study")
    study.optimize(
        lambda trial: optuna_objective_global(trial, folds_data),
        n_trials=N_TRIALS,
        show_progress_bar=True,
    )

    best_params = study.best_params
    best_value = study.best_value  # 这是 -mean_R2
    print("\nBest params (global across 5 folds):")
    for k, v in best_params.items():
        print(f"  {k}: {v}")
    print(f"Best objective value (=-mean_R2): {best_value:.6f}")
    print(f"Corresponding mean_R2 ≈ {-best_value:.6f}")

    # 保存 Optuna trials 表
    trials_df = study.trials_dataframe(attrs=(
        "number", "value", "params", "state"
    ))
    trials_df.to_csv(MODEL_DIR / "optuna_trials_xgb_source_kfold.csv", index=False)
    print(f"\nSaved Optuna trials to: {MODEL_DIR / 'optuna_trials_xgb_source_kfold.csv'}")

    # 3. 用全局最佳超参数，在每一折上重新训练模型，并保存模型和元信息
    print("\n=== Train & Save models for each fold with global best params ===")

    # 固定的一些参数（和上面 objective 里保持一致）
    fixed_params = {
        "objective": "reg:squarederror",
        "eval_metric": "rmse",
        "booster": "gbtree",
        "tree_method": "hist",
        "random_state": 42,
        # 如果在最佳参数里没有 n_jobs 而你想限制线程，也可以在这里设置
        "n_jobs": 8,
    }

    results = []

    for fold in range(1, 6):
        print(f"\n========== Evaluate with global best params | Fold {fold} ==========")

        X_train = folds_data[fold]["X_train"]
        y_train = folds_data[fold]["y_train"]
        X_test  = folds_data[fold]["X_test"]
        y_test  = folds_data[fold]["y_test"]
        df_train = folds_data[fold]["df_train"]
        df_test  = folds_data[fold]["df_test"]

        # 合并固定参数和搜索得到的最佳参数
        model = xgb.XGBRegressor(
            **fixed_params,
            **best_params,  # 覆盖可调参数
        )

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        r2 = r2_score(y_test, y_pred)
        mae = mean_absolute_error(y_test, y_pred)

        print(f"Fold {fold} | R2 = {r2:.4f}, MAE = {mae:.4f}")

        # 记录结果
        res = {
            "fold": fold,
            "n_train": int(len(y_train)),
            "n_test": int(len(y_test)),
            "n_train_sources": int(df_train["source_key"].nunique()),
            "n_test_sources": int(df_test["source_key"].nunique()),
            "R2": float(r2),
            "MAE": float(mae),
        }
        results.append(res)

        # 3.1 保存模型（包含超参数和拟合状态）
        model_path = MODEL_DIR / f"xgb_fold{fold}.joblib"
        dump(model, model_path)
        print(f"Saved model for fold {fold} to: {model_path}")

        # 3.2 保存该折的元信息（不重复保存整个数据，只保存必要信息）
        meta = {
            "fold": fold,
            "model_path": str(model_path),
            "feature_cols": feature_cols,
            "target_col": target_col,
            "params_fixed": fixed_params,
            "params_best": best_params,
            "n_train": int(len(y_train)),
            "n_test": int(len(y_test)),
            "n_train_sources": int(df_train["source_key"].nunique()),
            "n_test_sources": int(df_test["source_key"].nunique()),
            "metrics": {
                "R2": float(r2),
                "MAE": float(mae),
            },
        }
        meta_path = MODEL_DIR / f"xgb_fold{fold}_meta.json"
        with open(meta_path, "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2, ensure_ascii=False)
        print(f"Saved metadata for fold {fold} to: {meta_path}")

    # 4. 汇总所有折结果并保存
    df_results = pd.DataFrame(results)
    print("\n===== Cross-fold results summary =====")
    print(df_results)
    print(
        f"\nMean R2 = {df_results['R2'].mean():.4f} ± {df_results['R2'].std():.4f}, "
        f"Mean MAE = {df_results['MAE'].mean():.4f} ± {df_results['MAE'].std():.4f}"
    )

    results_path = MODEL_DIR / "xgb_source_kfold_results.csv"
    df_results.to_csv(results_path, index=False)
    print(f"\nSaved fold-wise results to: {results_path}")


if __name__ == "__main__":
    main()
